### ISSUE TITLE
Add (verbose) tool tip on star button for persisting experiment

### ISSUE THREAD

**Issue by tarelli** [OpenSourceBrain/geppetto-osb#14]
Also tool tips on Run, Play etc. would be useful explaining difference between them, when they can be used etc.

See https://github.com/openworm/org.geppetto/issues/459

**Comment by pgleeson** [comment]
Feedback from @MRIO:

I thought I’d share that I find the word choice  ‘persist’ a little opaque. Maybe better ‘activate’, or ‘enable simulation’ as floating text, or even ‘make ready to run’?

Also, as a suggestion: if someone clicks on the grayed out star, because he’s logged off, might be good to advise the user.

**Comment by mattearnshaw** [comment]
"Click star to save and enable simulation" is shown on load https://github.com/OpenSourceBrain/geppetto-osb/commit/b463e7c5bee8c6ad9694903a492f722f95b34e85

**Comment by mattearnshaw** [comment]
star -> floppy disk
tooltip on disabled persist

**Comment by pgleeson** [comment]
Done
