### ISSUE TITLE
Evaluate current Django backend vs moving to Jupyter Notebook/Hub backend

### ISSUE THREAD

**Issue by tarelli** [OpenSourceBrain/geppetto-osb#183]
- [x] Prototype Jupyter based deployment
- [x] Create a document and link it to this card with the analysis. What code will have to change? What's the time estimate for the different bits? Create LucidChart diagram if needed.

**Comment by filippometacell** [comment]
The porting on Jupyter has been completed.
The main points in the porting from Django to Jupyter have been the following:

- Reengineered the jupyter-geppetto in order to allow the application to add more http routes. A simple 'hook' mechanism has implemented with the branch extensible routes: https://github.com/openworm/org.geppetto.frontend.jupyter/tree/feature/extensible_routes. Now the application can add routes by adding them to the application library. This works and it's perfectly generic but I'm not really happy with the result to be considered finished. A tornado handler for each path must be defined. So we have a tornado handler for the load functionality, another handler for the plot functionality, and so on. This is due to the lacking of a proper controller mechanism as we have in Django. With 2 more day of work we could set up a proper controller mechanism like the Django's one (provided that we really want each application to define its own api, see below).
- Implemented the routes on the nwb_explorer module for the APIs defined in Django
- Changed the paths and details on the callbacks on the API calls. There are slight differences in the way tornado returns the data (I suppose MIME types), so the JSON were loaded directly without the need of JSON.loads
- Inserted the python calls to module loading in the ComponentInitialization
- Implemented a simple caching mechanism for generated models, which happens to be really slow for large files.


TODOs, considerations:
- Dynamic file loading. file to load is still hardcoded. How much work is needed to dynamically load the files depends on the source we want to adopt. Considering the first, easiest, solution to load the file from a public url parameter it could be implemented with a day of work. I still have a doubt related to the Jupyterhub spawning mechanism. Consider the scenario in which the user is clicking to a nwb file on a OSB project. This spawns a fresh new NWB explorer envirnoment which should show the specified file. Are we able to pass this to the pod we're freshly creating from the url? @rodriguez-facundo any idea about this?
- Still with this refactoring we don't have the possibility to have different frontend applications on the same Jupyter notebook at the same time. This would require having a different base path for each frontend application. Another solution, faster but less robust I think, would be to take out all the routing definition on the application, which should take care of the paths manually.
- Make the flow more consistent with Java-based applications. The main reason why we need to extend the REST API is related to the fact that the Python backend is not implementing the extensible functionalities that we have on the Java backend. We're loading the data with a custom API, we're showing the plots with a custom API. This gives more freedom for sure and has fasten the development for now, but this naturally leads to the development of not reusable functionalities (e.g. the nice holoviews plots implemented here are generated in the backend and sent with custom api). The risk of definitely diverging the functionalities available in Python-based applications and Java-based ones is high. This work could start from a branch started by Vincent.(https://github.com/openworm/pygeppetto/tree/feature/managers if I'm correct). More analysis is needed to make a decent estimate.
- File caching. NWB files are big and slow to load, much slower to download. We need a shared storage or database to use as cache. The code to load the cache from file system is already there, but needs some refactor and possibly rework after the file loading mechanism has been set up. Implement the simplest caching mechanism: 1 day. Set up the shared space: 1 day
- Features? At the time, the only functionality available is loading a file and showing the available plots. @tarelli More analysis is required to define the detailed functionalites we want to make available for April (or this may be enough?)
- Python notebook interaction. It's not really clear what can the user do within the Jupyter notebook. This is a problem shared with the other Jupyter-geppetto applications. I'd suppose to have the variables I see in the interface already there, or at least something that says how to load the data. At the moment is not much more than a Notebook with all the libraries already installed and available. With more than one application, this problem is more evident with the added confusion of having two frontends.
