### ISSUE TITLE
Investigate the best option to spawn different applications with JupyterHUB

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#213]

**Comment by rodriguez-facundo** [comment]
### Summary
- Jupyterhub allows the user to select a container for spawning but you have to use an HTML form. 
- There is another option which is name servers, where you can have multiple servers in a single container for a single user, and you switch between them like this:
```
IP/users/2837-3234-2345-6577/servers/server1
IP/users/2837-3234-2345-6577/servers/server2
```
but that requires some work in the spawner class in order to make it work (because we don't want the user to select the spawner from a form). I have an idea to make it work, but it will require some coding around the authentication and spawner classes and the tornado handlers.

#### Current working example
I managed to deploy 2 different applications in a single Kubernetes cluster by using 2 deployments. Each one with a different entry point, HTTP proxy and hub.
