### ISSUE TITLE
Make NWB explorer working with a minimal set of files

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#219]
The format and the pynwb library seem quite unstable: the file that was working on the showcase cherry pick of the pynwb library is not working anymore and we're getting errors also from the simplest files suggested by Padraig.
For the first release, we should agree on a minimal set of files and functionalities which we are supporting and make the NWB Explorer application working with that files.

**Comment by pgleeson** [comment]
Yes, it's a bit of a moving target, but NWB2 is now released, so any breakages are valid for reporting as issues...

**Comment by filippometacell** [comment]
Here we'd like to have a minimal set for the first releases, in the sense that this is what we're going to give priority because it's something going on demos and presentations. This because the NWB2 implementation is like a living thing right now, and we need some boundary of certainty to test the application.
This boundary may move of course, and does not represent a limit of what we're going to support in the future.
