### ISSUE TITLE
Make NWB Explorer work with Padraig's NWB files

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#220]
Not all the resources in the Padraig's NWB repo seem to be available at the moment to build the files. Some help may be required from the pynwb team (use the slack channel)

- [x] Fix https://github.com/OpenSourceBrain/NWBShowcase/blob/master/NWB/time_series_data.nwb?raw=true
- [x] Fix https://github.com/OpenSourceBrain/NWBShowcase/blob/master/FergusonEtAl2015/FergusonEtAl2015.nwb
- [ ] Generate file from https://github.com/OpenSourceBrain/NWBShowcase/tree/master/ScholzEtAl2019 (ask Padraig) and get it to work
- [ ] Generate file from https://github.com/OpenSourceBrain/NWBShowcase/tree/master/TriplettEtAl2018 (ask Padraig) and get it to work

**Comment by pgleeson** [comment]
Mainly because the original data is quite large.. but should have clearer instructions on how to get the data/which files...

Note though that the only example currently trying to save the data in valid nwb is Ferguson (I'm still learning the ins and outs of pynwb). The others just try to extract/display the data... It might be good to hunt on the pynwb site more more currently valid nwb2 files...

**Comment by filippometacell** [comment]
Unfortunately I haven't found anything in the site. We're planning to ask to the dev team if they have something. My assumption here is that is good to have an "independent" source of data to check the robustness of the solution.

**Comment by filippometacell** [comment]
We are at a point that we can load the time series within the files provided that they are loaded as TimeSeries objects.
We have a 5GB file which is loading fastly with a 1000 point resampling on the time series.
I'd consider this as completed even without the other two datasets, since we don't expect anything new coming from the data by itself.
