### ISSUE TITLE
Handle spatial timeseries in NWB files

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#225]
In the current implementation [spatial timeseries](https://nwb-schema.readthedocs.io/en/latest/format.html#sec-spatialseries) are being splitted into single mono-dimensional one. 3D plots may be best suited for 2 dimensions, other plots (maybe) for bigger dimension?

**Comment by filippometacell** [comment]
Example: https://github.com/OpenSourceBrain/NWBShowcase/blob/master/ScholzEtAl2019/Testing.ipynb

**Comment by filippomc** [comment]
Also Yuta mouse experiments feature spatial time series. In this case we have lots of points recorded, so we must look at rendering performance (20MB about une spatial time series uncompressed, 5MB compressed). @pgleeson are we interested in keeping the time resolution of the data unchanged for showing spatial data? May we think on setting a limit on spatial resolution (e.g. three significant digits)?

**Comment by pgleeson** [comment]
Certainly a 2D representation of this should be sufficient for now. I would assume that 3 sig digits should be ok for rendering this. It raises the question for each plot though, will there be a link (toolbar button etc.) which will allow download of the original data points, rather than the data used in the plot...

Longer term it might be better having a 2D plot where the point on the plot moved over time (e.g. following the position of the mouse/worm). If there is other data which is recorded over the same epoch/time series (e.g. cell recording, running speed, or video) these plots/videos could be synchronously replayed too with one global time controller. Would be more informative than a 3D plot of the spatial timeseries.

**Comment by filippomc** [comment]
Moving to NWB explorer repo
