### ISSUE TITLE
Investigate CMS solution for new OSB website

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#285]
Requirements:
 - Python or node based
 - Headless (REST-api based)
 - Lighweight - allow for content editing, menus
 - Modern

- [ ] Investigate
- [ ] Create a PoC

**Comment by zsinnema** [comment]
After searching the web I found these two most interesting: 
* PHP based: https://directus.io/ (self hosted no license fee),   https://github.com/directus/directus  
* Python based: https://wagtail.io/about-wagtail/ (open source, no license fee), 
 https://github.com/wagtail/wagtail

# things to discuss:
* GraphQL support
* authentication should be part of CMS

Other interesting ones are
* https://buttercms.com/python-cms/ (license fee)
* https://www.storyblok.com/ (license fee)
* https://www.cosmicjs.com/ (license fee) cloud based
* https://prismic.io/ (license fee) cloud based

**Comment by filippomc** [comment]
Hi @zsinnema surely free/open-source is a requirement. After some shared analysis authentication using keycloak is the favourite option, REST api based rather than GraphQL for consistency with other apis. Have you also looked at node solutions like strapi and ghost?

**Comment by filippomc** [comment]
Check a third gihub based solution

**Comment by zsinnema** [comment]
At the moment of writing these 2 CMS systems seem to be most interesting
* Wagtail (python & django)
* Strapi (nodejs)

Both are easy to customize and flexible. Also both have an API for retrieving the CMS data in JSON format so it can be used in the/a react frontend.

Because wagtail is a python & django based CMS there is a good integration with Keycloak
Strapi has no Keycloak integration so we need to write this one. The documentation describes how to
