### ISSUE TITLE
Plan legacy geppetto-osb to live

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/geppetto-osb#287]
- [ ] Analyse status of the Geppetto-osb application (high level)
- [ ] Check current status of the deployment
- [ ] Check what's not working in the deployment coming from codefresh (e.g the react branch of geppetto-osb)
- [ ] Check what's deployed on live (apps, volumes, branches, etc)
- [ ] Make cards to come to the release

**Comment by zsinnema** [comment]
- osb application. the current repo contains many branches. The react branch has both old as new code. The docker build is not working because of changes in the setup (old code)
the most latestes branches are "react" (27 Nov 2019) and "osbDevelopment" branch (19 Nov 2019).
both branches fail when building the Docker image.
last development commit is 1 March 2018 this one also doesn't build
these are the issues:
1. python2 vs python3
2. required repos (branch development) are updated with new structures (e.g. geppetto client)
3. apache maven version 3.5.0 doesn't exist anymore

- current deployment status: unknown

- current codefresh deployment whats working: unknown (I asked Facundo if the deployment ever ran...)
- AWS deployment: waiting for credentials

**Comment by pgleeson** [comment]
@zsinnema  Have you looked through the branches as used here: https://github.com/SilverLabUCL/docker-osb?

**Comment by zsinnema** [comment]
@pgleeson when I try to register locally I get an error message: Error! reCAPTCHA verification failed, please try again.

I think I'm missing a key or so

**Comment by pgleeson** [comment]
@zsinnema Best if the recaptcha is disabled on local install. See https://github.com/OpenSourceBrain/redmine/issues/326
