### ISSUE TITLE
3D view broken on beta

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#322]
e.g. https://beta.opensourcebrain.org/projects/hodgkin-huxley-tutorial/models?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fopenworm%252Fhodgkin_huxley_tutorial%252Fmaster%252FTutorial%252FSource%252FHHCellSingleAP.net.nml

<img width="655" alt="Screenshot 2020-04-24 at 12 19 04" src="https://user-images.githubusercontent.com/1556687/80207297-d2fe1400-8625-11ea-8d91-7696d96773b4.png">

Any ideas @zsinnema?

**Comment by zsinnema** [comment]
After I've recreated the images and deployed them using the Codefresh pipeline it seems to work again.

May be this issue is related to this https://github.com/OpenSourceBrain/geppetto-osb/issues/317#issuecomment-618952011

It could be that when there are not enough resources available the system stops working.

@pgleeson can you tell me how I can schedule the NSG simulation you tried?

**Comment by pgleeson** [comment]
Working nicely now on beta, thanks. 

For NSG, see https://github.com/OpenSourceBrain/geppetto-osb/issues/317 for how to submit to NSG. Try running a model e.g. with NEURON on OSB first, then clone the completed experiment before trying it on NEURON on NSG:

<img width="253" alt="Screenshot 2020-04-28 at 11 51 56" src="https://user-images.githubusercontent.com/1556687/80479313-becc5680-8946-11ea-83ef-563df967bc5f.png">

Tried today, still failing (going red, should go to yellow & stay for a few hours, but at least get submitted).
