### ISSUE TITLE
Ensure same colours are used in connectivity widgets for populations as are taken from nml file & used for 3d cells

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#46]
These would be better if colours matched:

![selection_286](https://user-images.githubusercontent.com/1556687/26871641-ccef33d4-4b6b-11e7-9925-8b9968c3aba8.png)

@borismarin mentioned that this should be relatively easy to do with an update to the method for opening the widget and passing parameters for the population colours as additional arguments

**Comment by borismarin** [comment]
That should do the trick:
- [ ] add an [optional argument](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/components/widgets/connectivity/Connectivity.js#L30) to the Connectivity widget model, called e.g. `nodeColormap` which will store a d3 colormap (described below)
- [ ] refactor the relevant widget types (`force`, `chord`, `hive`, to take this colour scale into account [instead of using a hardcoded one](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/components/widgets/connectivity/forces.js#L15) - notice the old `TODO` comment regarding this fact...)
- [ ] use the Geppetto NeuroML API (do we still call it 'NeuroML model interpreter'?) to build a `population_name -> colour ` mapping
- [ ] from this mapping (which doesn't need to be built explicitly) construct a [d3 ordinal colour scale](https://github.com/d3/d3-scale/blob/master/README.md#scaleOrdinal) whose _domain_ contains the population names, and the _range_ each one of the colours (RGB hex strings)
- [ ] when creating an instance of the widget (via console), pass the d3 ordinal scale constructed above to `nodeColormap` , as well as a `nodeType` callback which will output the parent population for each node (`node -> population` mapping).

**Comment by mattearnshaw** [comment]
working prototype (for chords so far) in progress at https://github.com/openworm/org.geppetto.frontend/tree/connectivity-colors

**Comment by borismarin** [comment]
@mattearnshaw @tarelli notice that I've suggested constructing the colormap at widget creation time, since ideally we shouldn't have [NeuroML specific (1)](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/components/widgets/connectivity/Connectivity.js#L113),[(2)](https://github.com/openworm/org.geppetto.frontend/blob/aa9998606b3338a468a0b84ece53d892b8cbb097/src/main/webapp/js/components/widgets/connectivity/Connectivity.js#L85) code in the widget.

**Comment by mattearnshaw** [comment]
- [ ] add test coverage (casper)
