### ISSUE TITLE
Performance issue with: Record all v at soma

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#51]
When there are many multicompartmental cells in a network (e.g. [here](http://comodl.org/projects/l23dendriticspikes/models?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FSmithEtAl2013-L23DendriticSpikes%252Fmaster%252FNeuroML2%252FL23_IV.net.nml)) and a simulation is set running but "Record all membrane potentials at soma" is run (not record in all segments) the window hangs and sometimes crashes. 

It seems even though just 9 values are specified to be recorded as in the above example, something is looping over all the 3K x 9 segments in the network...

**Comment by tarelli** [comment]
@pgleeson I think that bit of code was changed by @mattearnshaw. Looking at this https://github.com/OpenSourceBrain/geppetto-osb/blob/development/ComponentsInitialization.js#L732 it seems like it's instantiating all variables even to just check whether we want to record them or not whether before we were only filtering according to the name. As a reminder calling getInstance results in a variable getting instantiated, i.e. going from it just being a string to an actual object with API etc. We instantiate variables only when the user actually tries to do something with them because otherwise when a model has many of them (multicompartmental ones for example) the browser won't handle all the variables being created.

**Comment by mattearnshaw** [comment]
for the time being I have reverted this in `development`
